### ISSUE TITLE
Project Abandoned?

### ISSUE THREAD

**Issue by mwillbanks** [siriwatknp/mui-treasury#1216]
@siriwatknp are you still maintaining the project or is it essentially deprecated / abandoned at this point?

**Comment by siriwatknp** [comment]
Not yet. I am still finding a proper stack for the infrastructure so that I can truly focus on the UI in the future. Also, I am waiting for the direction of [MUI's Material You](https://github.com/mui/material-ui/issues/29345) package because that would impact this project as well.

By the way, do you find this project useful? What do you like to see next?

**Comment by smartdeepp** [comment]
i will be more than happy to see this package grow more and more. :smile:rocket:

**Comment by Gimnath-Perera** [comment]
@siriwatknp count me in

**Comment by siriwatknp** [comment]
Hello everyone. Happy New Year, the [new website](https://mui-treasury.com/) has been launched, please check it out and let me know how it goes!
