### ISSUE TITLE
anchor: 'left' prop for content

### ISSUE THREAD

**Issue by stevenarvar** [siriwatknp/mui-treasury#549]
Hi

Thanks for this nice project.  I started using it in experiment.  I noticed the content has persistentBehavior prop only.  Playing with layout, I feel the left sidebar menu is too far way from a centered content on web browser.  Gmail has its content attached to its sidebar which allows user to navigate the sidebar from content easily.  When the content is centered and the window is wide enough, it creates an uncomfortable white space also the page looks unbalanced.  I am wondering if you would add more positioning props to the content.

**Comment by siriwatknp** [comment]
If you could provide some image that explain your thought, that would be very helpful.

**Comment by siriwatknp** [comment]
I think I get your point. The demo or example in the site use `Container` that's why there is a gap when screen is large. However, the container is not a dependency of @mui-treasury/layout, you still have full control inside `Content`.

I will close this issue since it is already doable with layout v3
