### ISSUE TITLE
publish multiple npm packages

### ISSUE THREAD

**Issue by mikestaub** [siriwatknp/mui-treasury#72]
I would like to be able to import all the components via an npm package.

Seeing as this repo has not been published yet, I suggest refactoring the project folder structure to have a `src/packages` folder for each exported package.

Besides @mui-treasury/peapods and @mui-treasury/core what else should we export?

**Comment by siriwatknp** [comment]
@mikestaub Cool! That's what I'm thinking about.

**Comment by mikestaub** [comment]
I will submit a PR with my proposal soon.

**Comment by Wizyma** [comment]
Hello ! 
instead of `src/packages`your could just have `packages`, why not refactor with lerna then add add a script `lerna publish` ?
And what would actually go to npm its what is inside `src/components`
Copy and paste is cool but if we can just install the components we want without increasing the amount of folder / files inside the project, it's even better

**Comment by yordis** [comment]
`/packages` - Independent and use `lerna`
`/src` - The existing `src` code for the website 🙂

This is what most people would expect in term of setup

**Comment by siriwatknp** [comment]
Hi, everyone. The project has been updated with packages!
You can pull it down and play around. The website use Gatsby and yarn workspace for manage packages.
@Wizyma I wonder how to put `publish` to CI (I use circle ci) when code changes
